COURSE_ACTS(COURSE_BOB, _(" 1 BOB-OMB BATTLEFIELD"),
       _("FUCK UP KING BOMB")     , _("FOOTRACE WITH KOOPA THE SlOW") , _("TWINKLE TWINKLE LITTLE STAR"),
       _("RED COINS BITCH")          , _("FAT ASS FLIES")        , _("GET EATEN BITCH"))

COURSE_ACTS(COURSE_WF, _(" 2 WHOMP'S FORTRESS"),
       _("CRUSH THE GRAVEL")        , _("CLIMB IT BITCH")    , _("CANNONS ARE FOR CASUALS"),
       _("MORE RED COINS BITCH"), _("FUCKING OWL")    , _("BETTER DO CANNONLESS"))

COURSE_ACTS(COURSE_JRB, _(" 3 JOLLY ROGER BAY"),
       _("DROWN MOTHERFUCKER")    , _("FUCK THIS EEL") , _("TREASURE CHESTS DONT DROWN"),
       _("RED COINS NOW")  , _("LEARN FRAMEWALK")     , _("METAL CAP IS USELESS"))

COURSE_ACTS(COURSE_CCM, _(" 4 COOL, COOL MOUNTAIN"),
       _("ICE SLIDE FOM HELL")             , _("SHUT THE FUCK UP PENQUIN")             , _("FAT PENGUIN RACE"),
       _("FROSTY SLIDE RED COINS BITCH")  , _("SNOWMAN")       , _("WALL KICKS WON'T WORK"))

COURSE_ACTS(COURSE_BBH, _(" 5 BIG BOO'S HAUNT"),
       _("KILL SOME GHOSTS")            , _("KILL MORE GHOSTS") , _("LIBRARY OF DOOM"),
       _("RED COINS MOFO")          , _("MORE BIG BOO")             , _("STOP STARING ASSHOLE"))

COURSE_ACTS(COURSE_HMC, _(" 6 HAZY MAZE CAVE"),
       _("ELEVATER CLIP")  , _("WORST REDS")       , _("MARIO CAN MOVE!"),
       _("DIE FROM POISON")     , _("BOX STAR")     , _("FUCKING ROCKS"))

COURSE_ACTS(COURSE_LLL, _(" 7 LETHAL LAVA LAND"),
       _("FUCK THE BIG BULLY")            , _("FUCK THE BULLIES")             , _("FREE REDS"),
       _("LOGS ARE FOR COWARDS")           , _("HOT RUN")  , _("HOT CLIMB"))

COURSE_ACTS(COURSE_SSL, _(" 8 SHIFTING SAND LAND"),
       _("THAT BIRD THAT I HATE") , _("DO YOU EVEN SHELL BRO")      , _("INSIDE THE STUPID PYRAMID"),
       _("SHELL OVER THE PILLARS"), _("FREE DYING FOR 8 RED COINS")   , _("PYRAMID ANNOYANCE"))

COURSE_ACTS(COURSE_DDD, _(" 9 DIRE, DIRE DOCKS"),
       _("SUB STAR")            , _("CHESTS OF DOOM")         , _("SLOW COINS"),
       _("NO METAL CAP ALLOWED")        , _("THE MANTA RAY'S RAGE")        , _("TANISH CAP"))

COURSE_ACTS(COURSE_SL, _("10 SNOWMAN'S LAND"),
       _("SNOWMAN'S BIG EGO")            , _("ICE BITCH")          , _("ICE MAZE"),
       _("YOU SPIN ME RIGHT AROUND")  , _("SHIT MORE RED COINS") , _("TANISH RETURNS"))

COURSE_ACTS(COURSE_WDW, _("11 WET-DRY WORLD"),
       _("TELEPORTER!")         , _("ALL THE WAY UP")               , _("SHITS IN THE SHALLOWS & SKY"),
       _("EXPRESS ELEVATOR--FUCK OFF!")   , _("GO TO HELL FOR RED COINS")      , _("TANISH THROUGH DOWNTOWN!"))

COURSE_ACTS(COURSE_TTM, _("12 TALL, TALL MOUNTAIN"),
       _("SCALE THE MOUNTAIN")            , _("MYSTERY OF THE MONKEY CAGE")    , _("SCARY 'SHROOMS, RED COINS"),
       _("MYSTERIOUS MOUNTAINSIDE")       , _("BREATHTAKING VIEW FROM BRIDGE") , _("BLAST TO THE LONELY MUSHROOM"))

COURSE_ACTS(COURSE_THI, _("13 TINY-HUGE ISLAND"),
       _("PLUCK THE PIRANHA FLOWER")      , _("THE TIP TOP OF THE HUGE ISLAND"), _("REMATCH WITH KOOPA THE QUICK"),
       _("FIVE ITTY BITTY SECRETS")       , _("WIGGLER'S RED COINS")           , _("MAKE WIGGLER SQUIRM"))

COURSE_ACTS(COURSE_TTC, _("14 TICK TOCK CLOCK"),
       _("ROLL INTO THE CAGE")            , _("THE PIT AND THE PENDULUMS")     , _("GET A HAND"),
       _("STOMP ON THE THWOMP")           , _("TIMED JUMPS ON MOVING BARS")    , _("STOP TIME FOR RED COINS"))

COURSE_ACTS(COURSE_RR, _("15 RAINBOW RIDE"),
       _("CRUISER CROSSING THE RAINBOW")  , _("THE BIG HOUSE IN THE SKY")      , _("COINS AMASSED IN A MAZE"),
       _("SWINGIN' IN THE BREEZE")        , _("TRICKY TRIANGLES!")             , _("SOMEWHERE OVER THE RAINBOW"))

SECRET_STAR(COURSE_BITDW, _("   BOWSER IN THE DARK WORLD"))
SECRET_STAR(COURSE_BITFS, _("   BOWSER IN THE FIRE SEA"))
SECRET_STAR(COURSE_BITS, _("   BOWSER IN THE SKY"))
SECRET_STAR(COURSE_PSS, _("   THE PRINCESS'S SECRET SLIDE"))
SECRET_STAR(COURSE_COTMC, _("   CAVERN OF THE METAL CAP"))
SECRET_STAR(COURSE_TOTWC, _("   TOWER OF THE WING CAP"))
SECRET_STAR(COURSE_VCUTM, _("   VANISH CAP UNDER THE MOAT"))
SECRET_STAR(COURSE_WMOTR, _("   WING MARIO OVER THE RAINBOW"))
SECRET_STAR(COURSE_SA, _("   THE SECRET AQUARIUM"))
SECRET_STAR(COURSE_CAKE_END, _(""))

CASTLE_SECRET_STARS(_("   CASTLE SECRET STARS"))

EXTRA_TEXT(0, _("ONE OF THE CASTLE'S SECRET STARS!"))
EXTRA_TEXT(1, _(""))
EXTRA_TEXT(2, _(""))
EXTRA_TEXT(3, _(""))
EXTRA_TEXT(4, _(""))
EXTRA_TEXT(5, _(""))
EXTRA_TEXT(6, _(""))
